//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Application.Core.Resources.Orders {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Order {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Order() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Application.Core.Resources.Orders.Order", typeof(Order).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House Nr.
        /// </summary>
        public static string Address_HouseNr {
            get {
                return ResourceManager.GetString("Address_HouseNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip-Code.
        /// </summary>
        public static string Address_PostalCode {
            get {
                return ResourceManager.GetString("Address_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Address.
        /// </summary>
        public static string Address_Street {
            get {
                return ResourceManager.GetString("Address_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Address_Town {
            get {
                return ResourceManager.GetString("Address_Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Address.
        /// </summary>
        public static string BillingAddress {
            get {
                return ResourceManager.GetString("BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Dispatch Date.
        /// </summary>
        public static string ChooseDispatchDate {
            get {
                return ResourceManager.GetString("ChooseDispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string CreateOrder {
            get {
                return ResourceManager.GetString("CreateOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Order Form.
        /// </summary>
        public static string CreateOrderForm {
            get {
                return ResourceManager.GetString("CreateOrderForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DeliveryAddress {
            get {
                return ResourceManager.GetString("DeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address Required.
        /// </summary>
        public static string DeliveryAddressRequired {
            get {
                return ResourceManager.GetString("DeliveryAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to Deliver.
        /// </summary>
        public static string DeliveryTime {
            get {
                return ResourceManager.GetString("DeliveryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Date.
        /// </summary>
        public static string DispatchDate {
            get {
                return ResourceManager.GetString("DispatchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Date cannot be in the past.
        /// </summary>
        public static string DispatchDateInpast {
            get {
                return ResourceManager.GetString("DispatchDateInpast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        public static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderId {
            get {
                return ResourceManager.GetString("OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Info.
        /// </summary>
        public static string OrderInfo {
            get {
                return ResourceManager.GetString("OrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Saved.
        /// </summary>
        public static string OrderSaved {
            get {
                return ResourceManager.GetString("OrderSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Updated.
        /// </summary>
        public static string OrderUpdated {
            get {
                return ResourceManager.GetString("OrderUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postalcode out of range.
        /// </summary>
        public static string PostalCodeOutOfRange {
            get {
                return ResourceManager.GetString("PostalCodeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Status_Completed {
            get {
                return ResourceManager.GetString("Status_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Processing.
        /// </summary>
        public static string Status_InProcessing {
            get {
                return ResourceManager.GetString("Status_InProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Transit.
        /// </summary>
        public static string Status_InTransit {
            get {
                return ResourceManager.GetString("Status_InTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item(s) Returned.
        /// </summary>
        public static string Status_Returned {
            get {
                return ResourceManager.GetString("Status_Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string Status_Withdrawn {
            get {
                return ResourceManager.GetString("Status_Withdrawn", resourceCulture);
            }
        }
    }
}
