//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Application.Core.Resources.Customers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Customer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Customer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Application.Core.Resources.Customers.Customer", typeof(Customer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Director.
        /// </summary>
        public static string AccountDirector {
            get {
                return ResourceManager.GetString("AccountDirector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE.
        /// </summary>
        public static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Appointment.
        /// </summary>
        public static string AddNewAppointment {
            get {
                return ResourceManager.GetString("AddNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        public static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Watchlist.
        /// </summary>
        public static string AddToWatchlist {
            get {
                return ResourceManager.GetString("AddToWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment/Visit.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Color.
        /// </summary>
        public static string AppointmentColor {
            get {
                return ResourceManager.GetString("AppointmentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppointmentDescription.
        /// </summary>
        public static string AppointmentDescription {
            get {
                return ResourceManager.GetString("AppointmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Icon.
        /// </summary>
        public static string AppointmentIcon {
            get {
                return ResourceManager.GetString("AppointmentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string Appointments {
            get {
                return ResourceManager.GetString("Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        public static string Assignment {
            get {
                return ResourceManager.GetString("Assignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments.
        /// </summary>
        public static string Assignments {
            get {
                return ResourceManager.GetString("Assignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy license.
        /// </summary>
        public static string BuyLicense {
            get {
                return ResourceManager.GetString("BuyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        public static string CallCenter {
            get {
                return ResourceManager.GetString("CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canvas/Visit.
        /// </summary>
        public static string Canvas {
            get {
                return ResourceManager.GetString("Canvas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case number.
        /// </summary>
        public static string Casenumber {
            get {
                return ResourceManager.GetString("Casenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Responsible.
        /// </summary>
        public static string CaseResponsible {
            get {
                return ResourceManager.GetString("CaseResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cases.
        /// </summary>
        public static string Cases {
            get {
                return ResourceManager.GetString("Cases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Title.
        /// </summary>
        public static string CaseTitle {
            get {
                return ResourceManager.GetString("CaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name Requierd.
        /// </summary>
        public static string CompanyNameRequired {
            get {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company URL http://www.url.com.
        /// </summary>
        public static string CompanyURL {
            get {
                return ResourceManager.GetString("CompanyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person.
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        public static string Corporation {
            get {
                return ResourceManager.GetString("Corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Appointment.
        /// </summary>
        public static string CreateAppointment {
            get {
                return ResourceManager.GetString("CreateAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Case.
        /// </summary>
        public static string CreateCase {
            get {
                return ResourceManager.GetString("CreateCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer.
        /// </summary>
        public static string CreateCustomer {
            get {
                return ResourceManager.GetString("CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer Form.
        /// </summary>
        public static string CreateCustomerForm {
            get {
                return ResourceManager.GetString("CreateCustomerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreatedBy.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string CustomerCustomer {
            get {
                return ResourceManager.GetString("CustomerCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string CustomerInfo {
            get {
                return ResourceManager.GetString("CustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Not Found.
        /// </summary>
        public static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Saved.
        /// </summary>
        public static string CustomerSaved {
            get {
                return ResourceManager.GetString("CustomerSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomersEmail.
        /// </summary>
        public static string CustomersEmail {
            get {
                return ResourceManager.GetString("CustomersEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Status.
        /// </summary>
        public static string CustomerStatus {
            get {
                return ResourceManager.GetString("CustomerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer status Requierd.
        /// </summary>
        public static string CustomerStatusRequierd {
            get {
                return ResourceManager.GetString("CustomerStatusRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Uploaded.
        /// </summary>
        public static string CustomersUploadedCount {
            get {
                return ResourceManager.GetString("CustomersUploadedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Type.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Updated.
        /// </summary>
        public static string CustomerUpdated {
            get {
                return ResourceManager.GetString("CustomerUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVR.
        /// </summary>
        public static string CVR {
            get {
                return ResourceManager.GetString("CVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish File.
        /// </summary>
        public static string DanishFile {
            get {
                return ResourceManager.GetString("DanishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days before repeat.
        /// </summary>
        public static string daysBeforeRepeat {
            get {
                return ResourceManager.GetString("daysBeforeRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEL-EAN.
        /// </summary>
        public static string DELEAN {
            get {
                return ResourceManager.GetString("DELEAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        public static string Demo {
            get {
                return ResourceManager.GetString("Demo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo Completed.
        /// </summary>
        public static string DemoCompleted {
            get {
                return ResourceManager.GetString("DemoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Excel File.
        /// </summary>
        public static string DownloadExcelFile {
            get {
                return ResourceManager.GetString("DownloadExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mileage Registration.
        /// </summary>
        public static string DrivingRegistration {
            get {
                return ResourceManager.GetString("DrivingRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN.
        /// </summary>
        public static string EAN {
            get {
                return ResourceManager.GetString("EAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ended.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ending.
        /// </summary>
        public static string Ending {
            get {
                return ResourceManager.GetString("Ending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndTime.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English File.
        /// </summary>
        public static string EnglishFile {
            get {
                return ResourceManager.GetString("EnglishFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated % Done.
        /// </summary>
        public static string ESTDoneLong {
            get {
                return ResourceManager.GetString("ESTDoneLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EST % Done.
        /// </summary>
        public static string ESTDoneShort {
            get {
                return ResourceManager.GetString("ESTDoneShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate.
        /// </summary>
        public static string Estimate {
            get {
                return ResourceManager.GetString("Estimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated.
        /// </summary>
        public static string Estimated {
            get {
                return ResourceManager.GetString("Estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Time Required.
        /// </summary>
        public static string EstimatedTimeRequired {
            get {
                return ResourceManager.GetString("EstimatedTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File max size is 100MB.
        /// </summary>
        public static string FileMaxSize {
            get {
                return ResourceManager.GetString("FileMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Assignments.
        /// </summary>
        public static string FinishedAssignments {
            get {
                return ResourceManager.GetString("FinishedAssignments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included in the daily report.
        /// </summary>
        public static string InReport {
            get {
                return ResourceManager.GetString("InReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoiced.
        /// </summary>
        public static string Invoiced {
            get {
                return ResourceManager.GetString("Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leads.
        /// </summary>
        public static string Leads {
            get {
                return ResourceManager.GetString("Leads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Assignment.
        /// </summary>
        public static string LinkedAssignment {
            get {
                return ResourceManager.GetString("LinkedAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Required.
        /// </summary>
        public static string NameRequierd {
            get {
                return ResourceManager.GetString("NameRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Attachment.
        /// </summary>
        public static string NoAttachment {
            get {
                return ResourceManager.GetString("NoAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Demostration.
        /// </summary>
        public static string NoDemonstration {
            get {
                return ResourceManager.GetString("NoDemonstration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Done.
        /// </summary>
        public static string NotDone {
            get {
                return ResourceManager.GetString("NotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Required.
        /// </summary>
        public static string NoteRequired {
            get {
                return ResourceManager.GetString("NoteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in the daily report.
        /// </summary>
        public static string NotInReport {
            get {
                return ResourceManager.GetString("NotInReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type.
        /// </summary>
        public static string NoType {
            get {
                return ResourceManager.GetString("NoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Vip Seller.
        /// </summary>
        public static string NoVipSeller {
            get {
                return ResourceManager.GetString("NoVipSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 14th Day.
        /// </summary>
        public static string P14D {
            get {
                return ResourceManager.GetString("P14D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Day.
        /// </summary>
        public static string P1D {
            get {
                return ResourceManager.GetString("P1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Month.
        /// </summary>
        public static string P1M {
            get {
                return ResourceManager.GetString("P1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every Year.
        /// </summary>
        public static string P1Y {
            get {
                return ResourceManager.GetString("P1Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2nd Day.
        /// </summary>
        public static string P2D {
            get {
                return ResourceManager.GetString("P2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2nd Month.
        /// </summary>
        public static string P2M {
            get {
                return ResourceManager.GetString("P2M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2nd Year.
        /// </summary>
        public static string P2Y {
            get {
                return ResourceManager.GetString("P2Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3rd Month.
        /// </summary>
        public static string P3M {
            get {
                return ResourceManager.GetString("P3M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3rd Year.
        /// </summary>
        public static string P3Y {
            get {
                return ResourceManager.GetString("P3Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 4th Month.
        /// </summary>
        public static string P4M {
            get {
                return ResourceManager.GetString("P4M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 6th Month.
        /// </summary>
        public static string P6M {
            get {
                return ResourceManager.GetString("P6M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 7th Day.
        /// </summary>
        public static string P7D {
            get {
                return ResourceManager.GetString("P7D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Person.
        /// </summary>
        public static string PrivatePerson {
            get {
                return ResourceManager.GetString("PrivatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of licenses.
        /// </summary>
        public static string ProcuctLicense {
            get {
                return ResourceManager.GetString("ProcuctLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Leader.
        /// </summary>
        public static string ProjectLeader {
            get {
                return ResourceManager.GetString("ProjectLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Company.
        /// </summary>
        public static string PublicCompany {
            get {
                return ResourceManager.GetString("PublicCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Table.
        /// </summary>
        public static string RefreshTable {
            get {
                return ResourceManager.GetString("RefreshTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove license.
        /// </summary>
        public static string RemoveLicense {
            get {
                return ResourceManager.GetString("RemoveLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats.
        /// </summary>
        public static string Repeats {
            get {
                return ResourceManager.GetString("Repeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarting.
        /// </summary>
        public static string Restarting {
            get {
                return ResourceManager.GetString("Restarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure, you want to close?.
        /// </summary>
        public static string RUSureClose {
            get {
                return ResourceManager.GetString("RUSureClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesPerson Email.
        /// </summary>
        public static string SalesPersonEmail {
            get {
                return ResourceManager.GetString("SalesPersonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesPerson Requierd.
        /// </summary>
        public static string SalesPersonRequierd {
            get {
                return ResourceManager.GetString("SalesPersonRequierd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Go to Notes.
        /// </summary>
        public static string SaveAndGoToNotes {
            get {
                return ResourceManager.GetString("SaveAndGoToNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Note on Customer Notes.
        /// </summary>
        public static string SaveNoteOnCustomer {
            get {
                return ResourceManager.GetString("SaveNoteOnCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts.
        /// </summary>
        public static string Starts {
            get {
                return ResourceManager.GetString("Starts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supported files are documents,text,,audio,video files and raster images.
        /// </summary>
        public static string SupportedFileTypes {
            get {
                return ResourceManager.GetString("SupportedFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Registration.
        /// </summary>
        public static string TimeRegistration {
            get {
                return ResourceManager.GetString("TimeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Registrations.
        /// </summary>
        public static string TimeRegistrations {
            get {
                return ResourceManager.GetString("TimeRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Town.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string TypeCustomer {
            get {
                return ResourceManager.GetString("TypeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead.
        /// </summary>
        public static string TypeLead {
            get {
                return ResourceManager.GetString("TypeLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string Types {
            get {
                return ResourceManager.GetString("Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdatedBy.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload customers from Excel Files.
        /// </summary>
        public static string UploadFromExcelFiles {
            get {
                return ResourceManager.GetString("UploadFromExcelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used time.
        /// </summary>
        public static string Usedtime {
            get {
                return ResourceManager.GetString("Usedtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid url .
        /// </summary>
        public static string ValidateURL {
            get {
                return ResourceManager.GetString("ValidateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email-address.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who plans the repeat?.
        /// </summary>
        public static string WhoPlansTheRepeat {
            get {
                return ResourceManager.GetString("WhoPlansTheRepeat", resourceCulture);
            }
        }
    }
}
