//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Application.Core.Resources.Administration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardLists {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardLists() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Application.Core.Resources.Administration.DashboardLists", typeof(DashboardLists).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New List.
        /// </summary>
        public static string AddNewList {
            get {
                return ResourceManager.GetString("AddNewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Procedure To List.
        /// </summary>
        public static string AddProcedureToList {
            get {
                return ResourceManager.GetString("AddProcedureToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to List.
        /// </summary>
        public static string AddToList {
            get {
                return ResourceManager.GetString("AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Desc.
        /// </summary>
        public static string ColumnDesc {
            get {
                return ResourceManager.GetString("ColumnDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name.
        /// </summary>
        public static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name Exist.
        /// </summary>
        public static string ColumnNameExist {
            get {
                return ResourceManager.GetString("ColumnNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name Required.
        /// </summary>
        public static string ColumnNameRequired {
            get {
                return ResourceManager.GetString("ColumnNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DashboardList.
        /// </summary>
        public static string CreateDashboardList {
            get {
                return ResourceManager.GetString("CreateDashboardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dashboard List Columns.
        /// </summary>
        public static string CreateDashboardListColumns {
            get {
                return ResourceManager.GetString("CreateDashboardListColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Dashboard List Columns Form.
        /// </summary>
        public static string CreateDashboardListColumnsForm {
            get {
                return ResourceManager.GetString("CreateDashboardListColumnsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create DashboardList Form.
        /// </summary>
        public static string CreateDashboardListForm {
            get {
                return ResourceManager.GetString("CreateDashboardListForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard List Columns.
        /// </summary>
        public static string DashboardListColumns {
            get {
                return ResourceManager.GetString("DashboardListColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashboardList is already added to dashboard.
        /// </summary>
        public static string DashboardlistDuplicate {
            get {
                return ResourceManager.GetString("DashboardlistDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DashboardList-Name Exists.
        /// </summary>
        public static string DashboardListNameExists {
            get {
                return ResourceManager.GetString("DashboardListNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Lists.
        /// </summary>
        public static string DashBoardLists {
            get {
                return ResourceManager.GetString("DashBoardLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete column?.
        /// </summary>
        public static string DeleteColumnMessageContent {
            get {
                return ResourceManager.GetString("DeleteColumnMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Column !.
        /// </summary>
        public static string DeleteColumnMessageTitle {
            get {
                return ResourceManager.GetString("DeleteColumnMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Widget.
        /// </summary>
        public static string DeleteWidget {
            get {
                return ResourceManager.GetString("DeleteWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete dashboardlist?.
        /// </summary>
        public static string DeleteWidgetConfirm {
            get {
                return ResourceManager.GetString("DeleteWidgetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error add dashboardlist to dashboard.
        /// </summary>
        public static string ErrorAddListToDashboard {
            get {
                return ResourceManager.GetString("ErrorAddListToDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error assign customer to list.
        /// </summary>
        public static string ErrorAssignCustomerToList {
            get {
                return ResourceManager.GetString("ErrorAssignCustomerToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Remove Customer From List.
        /// </summary>
        public static string ErrorRemoveCustomerFromList {
            get {
                return ResourceManager.GetString("ErrorRemoveCustomerFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Remove DashboardList.
        /// </summary>
        public static string ErrorRemoveWidget {
            get {
                return ResourceManager.GetString("ErrorRemoveWidget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to my Dashboard.
        /// </summary>
        public static string GotoMyDashboard {
            get {
                return ResourceManager.GetString("GotoMyDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Description.
        /// </summary>
        public static string ListDescription {
            get {
                return ResourceManager.GetString("ListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        public static string ListName {
            get {
                return ResourceManager.GetString("ListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name Exist.
        /// </summary>
        public static string ListNameExist {
            get {
                return ResourceManager.GetString("ListNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name Required.
        /// </summary>
        public static string ListNameRequired {
            get {
                return ResourceManager.GetString("ListNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Lists.
        /// </summary>
        public static string Lists {
            get {
                return ResourceManager.GetString("Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Saved.
        /// </summary>
        public static string ListSaved {
            get {
                return ResourceManager.GetString("ListSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Updated.
        /// </summary>
        public static string ListUpdated {
            get {
                return ResourceManager.GetString("ListUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Dashboard.
        /// </summary>
        public static string MyDashBoard {
            get {
                return ResourceManager.GetString("MyDashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My DashBoard Lists.
        /// </summary>
        public static string MyDashBoardLists {
            get {
                return ResourceManager.GetString("MyDashBoardLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Customer.
        /// </summary>
        public static string RemoveCustomer {
            get {
                return ResourceManager.GetString("RemoveCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove customer from list?.
        /// </summary>
        public static string RemoveCustomerConfirm {
            get {
                return ResourceManager.GetString("RemoveCustomerConfirm", resourceCulture);
            }
        }
    }
}
