//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Application.Core.Resources.Email {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Application.Core.Resources.Email.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Email Account.
        /// </summary>
        public static string AttachEmailAccount {
            get {
                return ResourceManager.GetString("AttachEmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concerning Customer.
        /// </summary>
        public static string ConcerningCustomer {
            get {
                return ResourceManager.GetString("ConcerningCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create-Email Form.
        /// </summary>
        public static string CreateEmailForm {
            get {
                return ResourceManager.GetString("CreateEmailForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Sent.
        /// </summary>
        public static string DateSent {
            get {
                return ResourceManager.GetString("DateSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will remove&lt;br/&gt;
        ///&amp;emsp;• The Email-account with address &lt;b&gt;$address&lt;/b&gt;,&lt;br/&gt;
        ///&amp;emsp;• Any customer-related email messags found in the account mailbox.
        /// </summary>
        public static string DeleteEmailAccountHTML {
            get {
                return ResourceManager.GetString("DeleteEmailAccountHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account.
        /// </summary>
        public static string EmailAccount {
            get {
                return ResourceManager.GetString("EmailAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Accounts.
        /// </summary>
        public static string EmailAccounts {
            get {
                return ResourceManager.GetString("EmailAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account Saved.
        /// </summary>
        public static string EmailAccountSaved {
            get {
                return ResourceManager.GetString("EmailAccountSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Account Updated.
        /// </summary>
        public static string EmailAccountUpdated {
            get {
                return ResourceManager.GetString("EmailAccountUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailMessage {
            get {
                return ResourceManager.GetString("EmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emails.
        /// </summary>
        public static string EmailMessages {
            get {
                return ResourceManager.GetString("EmailMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Server.
        /// </summary>
        public static string EmailServer {
            get {
                return ResourceManager.GetString("EmailServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailAccount.
        /// </summary>
        public static string FetchedFrom {
            get {
                return ResourceManager.GetString("FetchedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Port.
        /// </summary>
        public static string HostPort {
            get {
                return ResourceManager.GetString("HostPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info could not be verified.
        /// </summary>
        public static string InvalidAccoount {
            get {
                return ResourceManager.GetString("InvalidAccoount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Synchronisation.
        /// </summary>
        public static string LatestSync {
            get {
                return ResourceManager.GetString("LatestSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string NoSyncAsOfYet {
            get {
                return ResourceManager.GetString("NoSyncAsOfYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Recipients {
            get {
                return ResourceManager.GetString("Recipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string RepeatPassWord {
            get {
                return ResourceManager.GetString("RepeatPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Emails.
        /// </summary>
        public static string ResendEmails {
            get {
                return ResourceManager.GetString("ResendEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncronize All.
        /// </summary>
        public static string SyncAll {
            get {
                return ResourceManager.GetString("SyncAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email-address.
        /// </summary>
        public static string ValidEmail {
            get {
                return ResourceManager.GetString("ValidEmail", resourceCulture);
            }
        }
    }
}
