//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Application.Core.Resources.Reports {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DailyReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DailyReport() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Application.Core.Resources.Reports.DailyReport", typeof(DailyReport).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Report.
        /// </summary>
        public static string DailyReportTitle {
            get {
                return ResourceManager.GetString("DailyReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump To Date.
        /// </summary>
        public static string JumpToDate {
            get {
                return ResourceManager.GetString("JumpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMFrom.
        /// </summary>
        public static string KMFrom {
            get {
                return ResourceManager.GetString("KMFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMTo.
        /// </summary>
        public static string KMTo {
            get {
                return ResourceManager.GetString("KMTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMTotal.
        /// </summary>
        public static string KMTotal {
            get {
                return ResourceManager.GetString("KMTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Date.
        /// </summary>
        public static string PreviousDate {
            get {
                return ResourceManager.GetString("PreviousDate", resourceCulture);
            }
        }
    }
}
